#define VERTEX_PACKING

#define CHUNK_SIZE_SHIFT 4
#define CHUNK_HEIGHT_SHIFT 8
#define CHUNK_SIZE (1 << CHUNK_SIZE_SHIFT)
#define CHUNK_HEIGHT (1 << CHUNK_HEIGHT_SHIFT)
#define CHUNK_SIZE_MASK ((1 << (CHUNK_SIZE_SHIFT + 1)) - 1)
#define CHUNK_HEIGHT_MASK ((1 << (CHUNK_HEIGHT_SHIFT + 1)) - 1)
